name: blockchain
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  intl: ^0.18.0
  provider: ^6.0.5
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
